#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys
from .ttypes import *
event_attr_capture_date = "capture_ts"
event_attr_capture_server_ip = "capture_server_ip"
event_attr_capture_server_fqdn = "capture_server_fqdn"
event_attr_inteceptor_id = "interceptor_id"
event_attr_inteceptor_protocol = "protocol_mnemo"
event_attr_print_copies = "print_copies"
event_attr_destination_type = "destination_type"
data_attr_email_subject = "subject"
data_attr_email_is_encrypted = "encrypted"
data_attr_email_is_signed = "is_signed"
data_attr_file_filename = "filename"
data_attr_file_source_file_path = "source_file_path"
data_attr_file_destination_file_path = "destination_file_path"
data_attr_voice_duration_sec = "call_duration"
data_attr_print_job_name = "print_job_name"
data_attr_print_copies = "print_copies"
data_attr_comment = "data_comment"
data_attr_mimetype = "mimetype"
data_attr_size = "data_size"
data_attr_sent_date = "sent_date"
identity_attr_ws_type = "workstation_type"
identity_attr_device_name = "device_name"
identity_attr_device_type = "device_type"
identity_attr_endpoint_name = "name"
identity_attr_endpoint_path = "path"
identity_attr_endpoint_type = "type"
identity_attr_endpoint_device_id = "device_id"
identity_attr_print_location = "print_location"
identity_attr_print_port_name = "print_port_name"
identity_attr_print_server = "print_server"
identity_attr_resource_url = "res_destination_url"
identity_attr_resource_address = "res_destination_host"
identity_attr_comment = "identity_comment"
ws_type_computer = "ws_type_computer"
ws_type_mobile = "ws_type_mobile"
ws_type_terminal = "ws_type_terminal"
link_name_ws = "workstation_link"
pushapi_version = 1
service_email = "email"
service_email_web = "email_web"
service_im_icq = "im_icq"
service_im_skype = "im_skype"
service_im_xmpp = "im_xmpp"
service_im_mmp = "im_mail_ru"
service_im_lync = "im_lync"
service_web = "web_common"
service_file_removable_storage = "file_copy_removable"
service_file_ftp = "ftp"
service_print = "print"
service_im_whatsapp = "im_whatsapp"
service_im_yahoo = "im_yahoo"
service_gsm = "gsm"
service_camera = "camera"
contact_type_email = "email"
contact_type_auth = "auth"
contact_type_dnshostname = "dnshostname"
contact_type_icq = "icq"
contact_type_skype = "skype"
contact_type_phone = "phone"
contact_type_ip = "ip"
contact_type_sid = "sid"
contact_type_webaccount = "webaccount"
contact_type_lotus = "lotus"
contact_type_domain = "domain"
